"""Shared domain constants for the TOR drafting application."""

from app.domain.tor_sections import (
    CRITICAL_SECTIONS_MIN_LENGTH,
    MINIMUM_CONTENT_LENGTH,
    ORPHAN_SECTIONS,
    SCOPE_SUBSECTIONS,
    STEP_SECTION_MAP,
    TOR_SECTION_LABELS,
    TOR_SECTION_LABELS_BILINGUAL,
    TOR_SECTION_ORDER,
    VALID_STEPS,
    WIZARD_STEP_COUNT,
)

__all__ = [
    "CRITICAL_SECTIONS_MIN_LENGTH",
    "MINIMUM_CONTENT_LENGTH",
    "ORPHAN_SECTIONS",
    "SCOPE_SUBSECTIONS",
    "STEP_SECTION_MAP",
    "TOR_SECTION_LABELS",
    "TOR_SECTION_LABELS_BILINGUAL",
    "TOR_SECTION_ORDER",
    "VALID_STEPS",
    "WIZARD_STEP_COUNT",
]
